source  'https://gitee.com/mirrors/CocoaPods-Specs.git’
# platform :ios, '9.0'

flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'FlutterBoostDemo' do

  use_frameworks!
  install_all_flutter_pods(flutter_application_path)


end
